### ISSUE TITLE
Not needed namespaceSelector in NetworkPolicy

### ISSUE THREAD

**Issue by lucj** [bmuschko/cks-crash-course#1]
The solution of the first exercise (https://github.com/bmuschko/cks-crash-course/blob/master/exercises/01-network-policy-restrict/solution/solution.md) defines the following NetworkPolicy:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-ingress
  namespace: g04
spec:
  podSelector:
    matchLabels:
      tier: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:    <-- This one is not needed
        matchLabels:
          app: orion
      podSelector:
        matchLabels:
          tier: frontend
    ports:
    - protocol: TCP
      port: 3000
 ```

The namespaceSelector is not needed as we want to allow the traffic from the frontend pod to the backend pod which are in the same g04 namespace.
